version: '3.7'

services:
  msforum-grpc-local:
    build: .
    container_name: msforum-grpc-local
    user: ${USER_ID}:${GROUP_ID}
    environment:
      HOME: /tmp/app/ # Set homedir to avoid permission issues
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - 3011:3000
      - 3011:3000/udp
    # command: npm run start:dev
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - msforum_network_local

  msforum-dynamodb-local:
    image: amazon/dynamodb-local
    container_name: msforum-dynamodb-local
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ."
    ports:
      - 8000
    volumes:
      - msforum_dynamodb_local:/data
    networks:
      - msforum_network_local

volumes:
  msforum_dynamodb_local:

networks:
  msforum_network_local: